name: promptfix
description: "AI destekli prompt oluşturma ve düzenleme uygulaması"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4
  google_mobile_ads: ^5.3.1
  http: ^1.4.0
  loading_indicator: ^3.1.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/play_store_512.png"
  min_sdk_android: 23
  adaptive_icon_foreground: "assets/play_store_512.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
